/* SPDX-License-Identifier: GPL-2.0-only */

#include "ns3/double.h"
#include "ns3/dv-cl-metric.h"
#include "ns3/dv-cl-toa.h"
#include "ns3/test.h"

namespace ns3
{
namespace dvcl
{
namespace test
{

/**
 * \ingroup dv-cl
 * F1.1: time-on-air equals Semtech AN1200.13 golden values.
 * Golden rows generated by test/reference/toa_reference.py (which also
 * checks the full 7296-combo grid against an independent implementation).
 */
class DvClToaGoldenTestCase : public TestCase
{
  public:
    DvClToaGoldenTestCase()
        : TestCase("dv-cl ToA matches Semtech AN1200.13 golden values")
    {
    }

  private:
    void DoRun() override
    {
        struct Row
        {
            uint8_t sf;
            uint32_t bw;
            uint8_t cr;
            uint32_t pl;
            bool de;
            uint32_t expectedUs;
        };

        // From test/reference/toa_golden.csv (explicit header, CRC on).
        const Row rows[] = {
            {7, 125000, 1, 20, false, 56576},
            {7, 125000, 1, 51, false, 102656},
            {7, 250000, 1, 51, false, 51328},
            {8, 125000, 1, 51, false, 184832},
            {9, 125000, 1, 51, false, 328704},
            {10, 125000, 1, 51, false, 616448},
            {11, 125000, 1, 51, true, 1314816},
            {12, 125000, 1, 51, true, 2465792},
            {12, 125000, 4, 51, true, 3547136},
            {7, 125000, 1, 1, false, 25856},
            {12, 125000, 1, 222, true, 8036352},
            {10, 125000, 2, 128, false, 1443840},
        };
        for (const auto& r : rows)
        {
            const uint32_t got = ComputeToaUs(r.sf, r.bw, r.cr, r.pl, false, r.de, true, 8);
            NS_TEST_ASSERT_MSG_EQ(got,
                                  r.expectedUs,
                                  "ToA mismatch at SF" << unsigned(r.sf) << " BW" << r.bw << " CR"
                                                       << unsigned(r.cr) << " PL" << r.pl << " DE"
                                                       << r.de);
        }
    }
};

/**
 * \ingroup dv-cl
 * F1.5 (unit part): composite metric analytic values, boundary cases and
 * monotonicity (more ToA => higher cost; less charge => higher cost).
 * Expected values computed by hand from the paper formula with defaults
 * (0.60, 0.15, 0.25), bLo=0.20, bHi=0.50, p=2, PsiMax=1.
 */
class DvClMetricAnalyticTestCase : public TestCase
{
  public:
    DvClMetricAnalyticTestCase()
        : TestCase("dv-cl composite metric analytic values and monotonicity")
    {
    }

  private:
    static LinkInputs In(double toaUs, uint8_t sf, double e)
    {
        LinkInputs in;
        in.toaUs = toaUs;
        in.sf = sf;
        in.energyFraction = e;
        return in;
    }

    void DoRun() override
    {
        auto m = CreateObject<DvClCompositeMetric>();
        const double tol = 1e-9;

        // Full battery, ToA at the SF7 ceiling: 0.60*1 + 0.15 + 0 = 0.75.
        NS_TEST_ASSERT_MSG_EQ_TOL(m->ComputeLinkCost(In(143360.0, 7, 1.0)),
                                  0.75,
                                  tol,
                                  "toaNorm=1, no penalty");

        // Zero ToA, boundary and interior battery values.
        NS_TEST_ASSERT_MSG_EQ_TOL(m->ComputeLinkCost(In(0.0, 7, 0.50)), 0.15, tol, "b=bHi: Psi=0");
        // b=0.35: Psi=((0.5-0.35)/0.3)^2=0.25 -> 0.25*0.25=0.0625.
        NS_TEST_ASSERT_MSG_EQ_TOL(m->ComputeLinkCost(In(0.0, 7, 0.35)),
                                  0.2125,
                                  tol,
                                  "b=0.35 interior ramp");
        NS_TEST_ASSERT_MSG_EQ_TOL(m->ComputeLinkCost(In(0.0, 7, 0.20)),
                                  0.40,
                                  tol,
                                  "b=bLo: full penalty 0.25");
        NS_TEST_ASSERT_MSG_EQ_TOL(m->ComputeLinkCost(In(0.0, 7, 0.05)),
                                  0.40,
                                  tol,
                                  "b<bLo saturates");
        // Unknown charge (<0) prices as full battery.
        NS_TEST_ASSERT_MSG_EQ_TOL(m->ComputeLinkCost(In(0.0, 7, -1.0)),
                                  0.15,
                                  tol,
                                  "unknown charge: no penalty");

        // Monotonicity in battery (lower b, higher cost).
        const double c45 = m->ComputeLinkCost(In(0.0, 7, 0.45));
        const double c30 = m->ComputeLinkCost(In(0.0, 7, 0.30));
        const double c15 = m->ComputeLinkCost(In(0.0, 7, 0.15));
        NS_TEST_ASSERT_MSG_GT(c30, c45, "penalty grows as b drops (0.30 vs 0.45)");
        NS_TEST_ASSERT_MSG_GT(c15, c30, "penalty grows as b drops (0.15 vs 0.30)");

        // Monotonicity in ToA at fixed battery.
        const double half = m->ComputeLinkCost(In(143360.0 / 2.0, 7, 1.0));
        const double full = m->ComputeLinkCost(In(143360.0, 7, 1.0));
        NS_TEST_ASSERT_MSG_GT(full, half, "cost grows with ToA");

        // ToA normalization caps at 1 above the ceiling.
        NS_TEST_ASSERT_MSG_EQ_TOL(m->ComputeLinkCost(In(10.0 * 143360.0, 7, 1.0)),
                                  0.75,
                                  tol,
                                  "toaNorm capped at 1");

        // Attribute plumbing: delta=0 disables the energy term.
        m->SetAttribute("WEnergy", DoubleValue(0.0));
        NS_TEST_ASSERT_MSG_EQ_TOL(m->ComputeLinkCost(In(0.0, 7, 0.05)),
                                  0.15,
                                  tol,
                                  "WEnergy=0 removes penalty");
    }
};

/**
 * \ingroup dv-cl
 * The dv-cl test suite, runnable with ./test.py -s dv-cl.
 */
/**
 * \ingroup dv-cl
 * rief Psi(b) is Eq. (psi) of the thesis, verbatim.
 *
 * Pins the piecewise energy penalty against the equation as written:
 *
 *   Psi(b) = 0                                        for b >= b_hi
 *          = Psi_max * ((b_hi - b)/(b_hi - b_lo))^p    for b_lo < b < b_hi
 *          = Psi_max                                   for b <= b_lo
 *
 * with b_lo = 0.20, b_hi = 0.50, p = 2, Psi_max = 1.
 *
 * The test exists because the repository's design document (February
 * 2026) specifies a different, threshold-free penalty (1 - b^2), and the
 * two are not interchangeable: above b_hi this one contributes exactly
 * nothing while 1 - b^2 never does, which decides whether the energy term
 * influences routing at all in a well-charged network. The thesis
 * equation is the one of record; this test keeps the code on it.
 *
 * EnergyPenalty returns delta*Psi, so the expectations carry the weight.
 */
class DvClThesisPsiTestCase : public TestCase
{
  public:
    DvClThesisPsiTestCase()
        : TestCase("dv-cl metric: Psi(b) matches Eq. (psi) of the thesis")
    {
    }

  private:
    void DoRun() override
    {
        auto metric = CreateObject<DvClCompositeMetric>();
        const double delta = 0.25; // WEnergy default; EnergyPenalty folds it in

        // b >= b_hi: no penalty at all. This is what makes a fully charged
        // network indistinguishable from a ToA-only metric.
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(1.00), 0.0, 1e-12, "b=1.00");
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(0.97), 0.0, 1e-12, "b=0.97");
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(0.50), 0.0, 1e-12, "at b_hi");

        // b <= b_lo: saturated at Psi_max.
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(0.20), delta, 1e-12, "at b_lo");
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(0.05), delta, 1e-12, "below b_lo");
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(0.00), delta, 1e-12, "empty");

        // Between the thresholds: the quadratic ramp, checked at points whose
        // value is exact. ((0.5-b)/0.3)^2 at b=0.35 is 0.25, at b=0.20+0.3/2.
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(0.35), delta * 0.25, 1e-12, "midpoint");
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(0.40),
                                  delta * (1.0 / 9.0),
                                  1e-12,
                                  "b=0.40 -> (1/3)^2");
        NS_TEST_ASSERT_MSG_EQ_TOL(metric->EnergyPenalty(0.30),
                                  delta * (4.0 / 9.0),
                                  1e-12,
                                  "b=0.30 -> (2/3)^2");

        // The ramp is monotone decreasing in charge, as a penalty must be.
        double prev = metric->EnergyPenalty(0.20);
        for (double b = 0.22; b <= 0.50; b += 0.02)
        {
            const double cur = metric->EnergyPenalty(b);
            NS_TEST_ASSERT_MSG_LT_OR_EQ(cur, prev, "penalty must not rise with charge");
            prev = cur;
        }
    }
};

class DvClTestSuite : public TestSuite
{
  public:
    DvClTestSuite()
        : TestSuite("dv-cl", Type::UNIT)
    {
        AddTestCase(new DvClToaGoldenTestCase, TestCase::Duration::QUICK);
        AddTestCase(new DvClMetricAnalyticTestCase, TestCase::Duration::QUICK);
        AddTestCase(new DvClThesisPsiTestCase, TestCase::Duration::QUICK);
    }
};

static DvClTestSuite g_dvClTestSuite; //!< static suite registration

} // namespace test
} // namespace dvcl
} // namespace ns3
